name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:testing
    steps:
    - uses: actions/checkout@v4
    - name: DoSomething
      run: |
        apt-get update; apt-get install -y arch-test e2fsprogs mmdebstrap qemu-system-x86 qemu-user-static uidmap zip unzip wget
        wget https://salsa.debian.org/helmutg/debvm/-/archive/main/debvm-main.tar.gz
        tar xf debvm-main.tar.gz
        cd debvm-main/
        ./bin/debvm-create

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: debvm-main/rootfs.ext4
